[skip ci]

diff --git a/prameworkcucutest/jenkinsfile b/prameworkcucutest/jenkinsfile
--- a/prameworkcucutest/jenkinsfile
+++ b/prameworkcucutest/jenkinsfile
@@ -1,92 +1,71 @@
 pipeline {
-
     agent any
 
-    tools {
-        maven 'Maven installations'
+    environment {
+        DOCKER = '/usr/local/bin/docker'
+        SELENIUM_URL = 'http://selenium-chrome:4444'
     }
 
     stages {
 
-        stage('Clean') {
-
+        stage('Checkout') {
             steps {
-
-                dir('prameworkcucutest') {
-
-                    sh 'mvn clean'
-                }
+                git branch: 'main',
+                    url: 'https://github.com/Pankajvis1/Wipro_Selenium_Training.git'
             }
         }
 
-        stage('Test') {
-
+        stage('Build Docker Image') {
             steps {
-
-                dir('prameworkcucutest') {
-
-                    sh 'mvn test'
-                }
+                sh '${DOCKER} build -t cucumber-framework .'
             }
+        }
+
+        stage('Create Network') {
+            steps {
+                sh '${DOCKER} network create selenium-net || true'
+            }
+        }
+
+        stage('Start Selenium') {
+            steps {
+                sh '''
+                ${DOCKER} rm -f selenium-chrome || true
+
+                ${DOCKER} run -d \
+                --name selenium-chrome \
+                --network selenium-net \
+                -p 4444:4444 \
+                selenium/standalone-chrome
+                '''
+
+                sh 'sleep 15'
+            }
+        }
+
+        stage('Run Tests') {
+            steps {
+                sh '''
+                ${DOCKER} run --rm \
+                --network selenium-net \
+                cucumber-framework \
+                mvn test \
+                -Dtest=Runner.RunCucumberTest \
+                -Dselenium.remote.url=http://selenium-chrome:4444
+                '''
+             }
         }
     }
 
     post {
-
-        success {
-
-            echo 'Build Successful'
-
-            emailext(
-                subject: "Jenkins Build Success - ${env.JOB_NAME}",
-
-                body: """
-                <h2>Build Successful</h2>
-
-                <p><b>Job Name:</b> ${env.JOB_NAME}</p>
-
-                <p><b>Build Number:</b> ${env.BUILD_NUMBER}</p>
-
-                <p><b>Build URL:</b>
-                <a href="${env.BUILD_URL}">
-                ${env.BUILD_URL}
-                </a></p>
-                """,
-
-                mimeType: 'text/html',
-
-                attachLog: true,
-
-                to: 'suryaprakashj32@gmail.com'
-            )
+        always {
+            sh '${DOCKER} rm -f selenium-chrome || true'
         }
-
+        success {
+            echo "BUILD SUCCESS"
+        }
         failure {
-
-            echo 'Build Failed'
-
-            emailext(
-                subject: "Jenkins Build Failed - ${env.JOB_NAME}",
-
-                body: """
-                <h2>Build Failed</h2>
-
-                <p><b>Job Name:</b> ${env.JOB_NAME}</p>
-
-                <p><b>Build Number:</b> ${env.BUILD_NUMBER}</p>
-
-                <p><b>Build URL:</b>
-                <a href="${env.BUILD_URL}">
-                ${env.BUILD_URL}
-                </a></p>
-                """,
-
-                mimeType: 'text/html',
-
-                attachLog: true,
-
-                to: 'suryaprakashj32@gmail.com'
-            )
+            echo "BUILD FAILED"
         }
     }
 }
